services:
    front:
        build: .
        container_name: avia-serve-front
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        networks:
            - avia-serve

networks:
    avia-serve:
        name: avia-serve
        external: true
