services:
    front:
        build: .
        container_name: avia-serve-front
        restart: unless-stopped
        ports:
            - '80:3000'
            - '443:3000'
        environment:
            - NODE_ENV=production
        networks:
            - avia-serve

networks:
    avia-serve:
        name: avia-serve
        external: true
